### ISSUE TITLE
Huge number of DNS-queries, can we reduce this?

### ISSUE THREAD

**Issue by ne20002** [sunsettrack4/easyepg#47]
Hi
I do love easyepg but I have an issue and wonder if this can be fixed. I hava a pi-hole running in my network and the queries from easyepg is messing up the statistics ... it's between ten thousends and up to 130 thousend queries to 'zattoo.com'.

Maybe its possible to add proper systemd-resolved caching?

**Comment by sunsettrack4** [comment]
The problem will be solved in my next version of easyEPG. The script will be able to combine multiple broadcast IDs to a single Zattoo API request. Please be patient, because the new version of my script is based on a different programming language (Python i/o Shell/Perl), and lots of features must be added first before releasing the script.

**Comment by Rumbelstilzchen** [comment]
Is there any update on this? Is there anything already available for testing?

**Comment by sunsettrack4** [comment]
I'm working on a new script / Kodi addon. This script reduces the number of requests to a minimum (all channels for Zattoo DE without cache: ~200 requests). An additional database system will store the data as well (= ~15 requests per day to be downloaded).
