### ISSUE TITLE
Horizon Service provider unavailable

### ISSUE THREAD

**Issue by WernerAUT** [sunsettrack4/easyepg#65]
Hi ist this issue related to easyepg or is it a  horizion issue?

```
 --------------------------------------------
 HORIZON EPG SIMPLE XMLTV GRABBER            
 powered by easyEPG Grabber v0.4.3 2020/01/11
 (c) 2019-2020 Jan-Luca Neumann / sunsettrack4    
 --------------------------------------------

+++ COUNTRY: AUSTRIA +++
Service provider unavailable!

Press any key to continue...
```

**Comment by sunsettrack4** [comment]
Fixed: https://github.com/sunsettrack4/easyepg/commit/d820cbd0e8a4d8af72797a2ab4e431c1778e833d

**Comment by WernerAUT** [comment]
thanks, tested and it works

**Comment by phill22** [comment]
i have the same problem since the last days :-(


 --------------------------------------------
 HORIZON EPG SIMPLE XMLTV GRABBER            
 powered by easyEPG Grabber v0.4.3 2020/01/11
 (c) 2019-2020 Jan-Luca Neumann / sunsettrack4    
 --------------------------------------------

+++ COUNTRY: AUSTRIA +++
Service provider unavailable!
